save_dir: ${launcher.experiment_log_dir}/checkpoints
save_freq: 25 # 0 only last checkpoint is saved.
model_weight_initializer:
  _partial_: True
  _target_: omnivision.model.checkpoint_utils.load_state_dict_into_model
  strict: False # heads aren't loaded
  state_dict:
    _target_: omnivision.model.checkpoint_utils.load_checkpoint_and_apply_kernels
    checkpoint_path: ${pretrained_checkpoint_path}
    ckpt_state_dict_key: model
    checkpoint_kernels:
    - _target_: omnivision.model.checkpoint_utils.CkptExcludeKernel
      key_pattern:
      - "trunk.decoder.*"
      - "trunk.norm.*"
      - "trunk.mask_token"
      - "heads.*"